version: "3.9"
services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/conf:/etc/mysql/conf.d
      - ./data/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tft_calendar
      MYSQL_USER: seungtaek
      MYSQL_PASSWORD: seungtaek
    restart: always
  mongodb:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: seungtaek
      MONGO_INITDB_ROOT_PASSWORD: seungtaek
      MONGO_INITDB_DATABASE: tft_calendar
  redis:
    image: redis:7
    ports:
      - "6379:6379"
