version: "3.9"
services:
  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./data/data:/var/lib/mysql
      - ./data/conf:/etc/mysql/conf.d
      - ./data/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tft_calendar
      MYSQL_USER: seungtaek
      MYSQL_PASSWORD: seungtaek
    restart: always
