spring:
  datasource:
    url: jdbc:mysql://${DB_URL:127.0.0.1/tft_calendar}
    name: ${DB_USER:seungtaek}
    password: ${DB_PASSWORD:seungtaek}
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  error:
    include-stacktrace: never
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: debug