spring:
  datasource:
    url: jdbc:mysql://${MYSQL_URL:localhost:3306/tft_calendar}
    name: ${MYSQL_USER:seungtaek}
    password: ${MYSQL_PASSWORD:seungtaek}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER:seungtaek}:${MONGODB_PASSWORD:seungtaek}@${MONGODB_URL:localhost:27017/tft_calendar?authSource=admin}
#  main:
#    web-application-type: none
server:
  error:
    include-stacktrace: never
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: debug
riot:
  api:
    token: ${RIOT_API_TOKEN}
